# Generated by Django 4.2.11 on 2024-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_address_alter_customuser_born_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='born_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
