# Generated by Django 4.2.11 on 2024-05-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_pass',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seria_pass',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
