# Generated by Django 4.2.11 on 2024-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_number_pass_customuser_seria_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='number_pass',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='seria_pass',
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
