# Generated by Django 4.2.11 on 2024-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
