# Generated by Django 4.2.11 on 2024-06-01 07:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chat_date_alter_chat_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Message',
        ),
    ]
