# Generated by Django 4.2.11 on 2024-06-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_rename_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
