# Generated by Django 4.2.11 on 2024-05-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mark',
            field=models.CharField(default=1, max_length=2, verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
