# Generated by Django 4.2.11 on 2024-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.IntegerField(max_length=2, verbose_name='Оценка'),
        ),
    ]
