# Generated by Django 4.2.11 on 2024-05-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mark_stars',
            field=models.CharField(default=1, max_length=5, verbose_name='Оценочные звёзды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='mark',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
    ]
