# Generated by Django 4.2.11 on 2024-05-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
