# Generated by Django 4.2.11 on 2024-06-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
