# Generated by Django 4.2.11 on 2024-04-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id_cart',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
