# Generated by Django 4.2.11 on 2024-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session',
        ),
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
