# Generated by Django 4.2.11 on 2024-05-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id_user',
        ),
    ]
