# Generated by Django 4.2.11 on 2024-06-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id_cart',
        ),
    ]
